version: "3.9"

services:
  sso-app:
    depends_on: [ sso-postgres ]
    build:
      dockerfile: .docker/sso-app.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app
  sso-postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: "sso-postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - app

networks:
  app: