version: "3.9"

services:
  sso-app:
    depends_on: [ sso-postgres ]
    build:
      dockerfile: .docker/sso-app.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app
    profiles:
      - infra
  sso-postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: "sso-postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - app
    profiles:
      - infra
  test:
    build:
      dockerfile: .docker/test.Dockerfile
    environment:
      BASE_URL: "http://sso-app:8080"
      DB_HOST: "sso-postgres"
    networks:
      - app
    profiles:
      - test
networks:
  app: